// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelApllication.Data;

namespace ModelApllication.Migrations
{
    [DbContext(typeof(PersoonKindContext))]
    [Migration("20180609124006_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ModelApllication.Entities.Kind", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Naam");

                    b.Property<string>("Voornaam");

                    b.Property<int?>("leeftijd");

                    b.HasKey("id");

                    b.ToTable("Kinderen");
                });

            modelBuilder.Entity("ModelApllication.Entities.Ouder", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("id");

                    b.ToTable("Ouders");
                });

            modelBuilder.Entity("ModelApllication.Entities.OuderKind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("Kindid");

                    b.Property<Guid?>("Ouderid");

                    b.HasKey("Id");

                    b.HasIndex("Kindid");

                    b.HasIndex("Ouderid");

                    b.ToTable("OurderKinderen");
                });

            modelBuilder.Entity("ModelApllication.Entities.OuderKind", b =>
                {
                    b.HasOne("ModelApllication.Entities.Kind", "Kind")
                        .WithMany("Ouder")
                        .HasForeignKey("Kindid");

                    b.HasOne("ModelApllication.Entities.Ouder", "Ouder")
                        .WithMany("Kind")
                        .HasForeignKey("Ouderid");
                });
#pragma warning restore 612, 618
        }
    }
}
